name: Build and Publish Worker

on:
  push:
    branches:
      - master
jobs:
  build_and_publish_worker:
    name: Build and Publish Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gcr.io/synthica/sc-worker:latest
